/** @file macros.h
*/#ifndef TENSORCORE_RESNET_COMMON_FUNCTIONAL_MACROS_H
#define TENSORCORE_RESNET_COMMON_FUNCTIONAL_MACROS_H

#define TESTT cout << "Alas!" << endl


#endif //TENSORCORE_RESNET_COMMON_FUNCTIONAL_MACROS_H
