#include "resnet.hpp"
#include "dataset.hpp"

using namespace Impl;
using namespace std;

int main() {
  // 1. load resnet18 model
  // 2. load image dataset
  // 3. inference

#ifdef DATASET_ROOT
#ifdef RESNET18_ROOT

  // TODO: argument parsing
#if SIMULATE
  cout << "Only simulate one round." << endl;
  auto dataset = Impl::ImageDataset(DATASET_ROOT, Impl::DeviceType::CUDA, 1);
#else
  auto dataset = Impl::ImageDataset(DATASET_ROOT, Impl::DeviceType::CUDA);
#endif
  string model_path = RESNET18_ROOT;
  model_path += "/resnet18";
  ResNet18 resnet18(model_path);
  resnet18.to(Impl::DeviceType::CUDA);
  resnet18.printModule("resnet18");
  std::cout << std::endl;

  int num_correct = 0;
  int num_total = 0;
  for (int i = 0; i < dataset.size(); i++) {
    auto data = dataset.next();
    auto result = std::move(resnet18.forward(std::move(data.first.first)));

    result.to(Impl::DeviceType::CPU);
    auto label = std::move(data.first.second);
    label.to(Impl::DeviceType::CPU);

    Tensor original_label = TensorOps::argmax(label, 1);
    Tensor predicted_result = TensorOps::argmax(result, 1);
    num_correct += (int) TensorOps::sum_equal(original_label, predicted_result);
    num_total += predicted_result.sizes()[0];
  }

  std::cout << "Accuracy Compared to PyTorch ResNet18 Implementation: " << num_correct << "/" << num_total << std::endl;

  return 0;

#endif
#endif

#ifndef DATASET_ROOT
  std::cout << "Dataset not found by CMake. Check CMake output." << std::endl;
#endif

#ifndef RESNET18_ROOT
  std::cout << "ResNet 18 weights not generated by CMake. Check CMake output." << std::endl;
#endif

}
